"""edit nullable hasil_kalkulasi

Revision ID: 37597e3e9f37
Revises: 8051d50d5328
Create Date: 2025-11-10 10:49:03.178012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37597e3e9f37'
down_revision: Union[str, Sequence[str], None] = '8051d50d5328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.alter_column('kv_r',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kv_s',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kv_t',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kw_r',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kw_s',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kw_t',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kvar_r',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kvar_s',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('kvar_t',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sisa_kap',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('waktu_kalkulasi',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('tgl_upload',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'group_trafo', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.alter_column('tgl_upload',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('waktu_kalkulasi',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('sisa_kap',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kvar_t',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kvar_s',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kvar_r',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kw_t',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kw_s',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kw_r',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kv_t',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kv_s',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('kv_r',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
