"""revisi table trafo per

Revision ID: 776c7a484e49
Revises: f2ccc6358bf1
Create Date: 2025-11-11 15:39:54.006557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776c7a484e49'
down_revision: Union[str, Sequence[str], None] = 'f2ccc6358bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltase_per', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_per', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_per')
        batch_op.drop_column('voltase_per')

    # ### end Alembic commands ###
