"""add table hasil_kalkulasi

Revision ID: 8051d50d5328
Revises: 91fe1ba117eb
Create Date: 2025-11-09 21:05:23.236147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8051d50d5328'
down_revision: Union[str, Sequence[str], None] = '91fe1ba117eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_kalkulasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_trafo', sa.Integer(), nullable=False),
    sa.Column('v_r', sa.Float(), nullable=False),
    sa.Column('v_s', sa.Float(), nullable=False),
    sa.Column('v_t', sa.Float(), nullable=False),
    sa.Column('i_r', sa.Float(), nullable=False),
    sa.Column('i_s', sa.Float(), nullable=False),
    sa.Column('i_t', sa.Float(), nullable=False),
    sa.Column('cosphi', sa.Float(), nullable=False),
    sa.Column('kv_r', sa.Float(), nullable=False),
    sa.Column('kv_s', sa.Float(), nullable=False),
    sa.Column('kv_t', sa.Float(), nullable=False),
    sa.Column('kw_r', sa.Float(), nullable=False),
    sa.Column('kw_s', sa.Float(), nullable=False),
    sa.Column('kw_t', sa.Float(), nullable=False),
    sa.Column('kvar_r', sa.Float(), nullable=False),
    sa.Column('kvar_s', sa.Float(), nullable=False),
    sa.Column('kvar_t', sa.Float(), nullable=False),
    sa.Column('sisa_kap', sa.Float(), nullable=False),
    sa.Column('waktu_kalkulasi', sa.DateTime(), nullable=False),
    sa.Column('tgl_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_trafo'], ['trafo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hasil_kalkulasi_id'), ['id'], unique=False)

    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'group_trafo', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hasil_kalkulasi_id'))

    op.drop_table('hasil_kalkulasi')
    # ### end Alembic commands ###
