"""revisi table hasil_kalkulasi

Revision ID: ed697798a16e
Revises: 37597e3e9f37
Create Date: 2025-11-11 14:11:40.708997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed697798a16e'
down_revision: Union[str, Sequence[str], None] = '37597e3e9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hasil_kalkulasi')
    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_kva', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_kvw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_kvar', sa.Float(), nullable=True))
        batch_op.alter_column('waktu_kalkulasi',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('tgl_upload',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'group_trafo', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trafo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hasil_kalkulasi', schema=None) as batch_op:
        batch_op.alter_column('tgl_upload',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('waktu_kalkulasi',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('total_kvar')
        batch_op.drop_column('total_kvw')
        batch_op.drop_column('total_kva')

    op.create_table('_alembic_tmp_hasil_kalkulasi',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_trafo', sa.INTEGER(), nullable=False),
    sa.Column('v_r', sa.FLOAT(), nullable=False),
    sa.Column('v_s', sa.FLOAT(), nullable=False),
    sa.Column('v_t', sa.FLOAT(), nullable=False),
    sa.Column('i_r', sa.FLOAT(), nullable=False),
    sa.Column('i_s', sa.FLOAT(), nullable=False),
    sa.Column('i_t', sa.FLOAT(), nullable=False),
    sa.Column('cosphi', sa.FLOAT(), nullable=False),
    sa.Column('kv_r', sa.FLOAT(), nullable=True),
    sa.Column('kv_s', sa.FLOAT(), nullable=True),
    sa.Column('kv_t', sa.FLOAT(), nullable=True),
    sa.Column('kw_r', sa.FLOAT(), nullable=True),
    sa.Column('kw_s', sa.FLOAT(), nullable=True),
    sa.Column('kw_t', sa.FLOAT(), nullable=True),
    sa.Column('kvar_r', sa.FLOAT(), nullable=True),
    sa.Column('kvar_s', sa.FLOAT(), nullable=True),
    sa.Column('kvar_t', sa.FLOAT(), nullable=True),
    sa.Column('sisa_kap', sa.FLOAT(), nullable=True),
    sa.Column('waktu_kalkulasi', sa.DATETIME(), nullable=True),
    sa.Column('tgl_upload', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_trafo'], ['trafo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
